/**
 * ESLint 9 flat config: extends Next.js core-web-vitals + TypeScript rules.
 * `ignores` skips build output and Next-generated `next-env.d.ts`.
 */
import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    ignores: [
      "**/.next/**",
      "**/node_modules/**",
      "**/out/**",
      "**/coverage/**",
      "**/*.min.js",
      /** Auto-generated by Next.js — triple-slash refs are required */
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      /* Disallow `any` — forces proper typing everywhere */
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
];

export default eslintConfig;
